#!/bin/bash
export commandfile='/var/spool/nagios/cmd/nagios.cmd'
export SERVICELIST=`grep 'service_description' /etc/nagios/services/*.cfg | awk '{print $3}' | sort | uniq | grep -i -P "$2"`
export HOSTLIST=`grep 'host_name' /etc/nagios/hosts/*.cfg | awk '{print $3}' | sort | uniq | grep -i -P "$1"`
SAVEIFS=$IFS
IFS=$(echo -en "\n\b")

for HOST in $HOSTLIST
do
  for SERVICE in $SERVICELIST
  do
    now=`date +%s`
    inabit=$(($now+10))
    echo "Scheduling $HOST $SERVICE"
    /usr/bin/printf "[%lu] SCHEDULE_FORCED_SVC_CHECK;$HOST;$SERVICE;$inabit\n" $now > $commandfile
  done
done
IFS=$SAVEIFS


